n_pretrain_steps: 128
n_finetune_steps: 64
n_context: 80
batch_size: 256
d_field: 64
max_pretrain_epochs: 1024
max_finetune_epochs: 2048
n_layers_field_encoder: 1
n_heads_field_encoder: 8
n_layers_event_encoder: 12
n_heads_event_encoder: 8
n_epochs_frozen: 32
learning_rate: 0.00000025
quantile_smoothing: 1.0
n_quantiles: 64
p_mask_event: 0.10
p_mask_field: 0.10
p_mask_static: 0.05
dropout: 0.1
patience: 128
jitter: 0.025
n_bands: 8
head_shape_log_base: 4
gradient_clip_val: 0.25
interpolation_rate: 0.075
learning_rate_dampener: 0.2
n_workers: 24
predict_only_sequence_end: false
