n_pretrain_steps: 64
n_finetune_steps: 128
n_context: 32
batch_size: 32
d_field: 96
max_pretrain_epochs: 4
max_finetune_epochs: 4
n_layers_field_encoder: 1
n_heads_field_encoder: 8
n_layers_event_encoder: 4
n_heads_event_encoder: 8
n_epochs_frozen: 1
learning_rate: 0.0000025
quantile_smoothing: 1.0
n_quantiles: 32
p_mask_event: 0.10
p_mask_field: 0.10
p_mask_static: 0.05
dropout: 0.1
patience: 2
jitter: 0.05
n_bands: 8
head_shape_log_base: 4
gradient_clip_val: 0.2
interpolation_rate: 0.08
learning_rate_dampener: 0.1
n_workers: 18
predict_only_sequence_end: false
