n_pretrain_steps: 512
n_finetune_steps: 72
n_context: 64
batch_size: 256
d_field: 96
max_pretrain_epochs: 1024
max_finetune_epochs: 1024
n_layers_field_encoder: 1
n_heads_field_encoder: 8
n_layers_event_encoder: 6
n_heads_event_encoder: 8
n_epochs_frozen: 32
learning_rate: 0.00001
quantile_smoothing: 0.000001
n_quantiles: 16
p_mask_event: 0.10
p_mask_field: 0.10
p_mask_static: 0.05
dropout: 0.1
patience: 64
jitter: 0.0
