repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: check-json
      - id: check-yaml
      - id: check-ast
      - id: end-of-file-fixer
        exclude: '(\.svg$|\.pdf$)'
      - id: trailing-whitespace
      - id: check-docstring-first

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.2"
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install

  # - repo: local
  #   hooks:
  #     - id: pytest-check
  #       name: pytest-check
  #       entry: just test
  #       language: system
  #       pass_filenames: false
  #       always_run: true
