[tool.poetry]
name = "windmark"
version = "0.1.0"
description = "Heterogenous Time Series Modeling"
authors = ["Windmark AI <dev@windmark.ai>"]
readme = "docs/README.md"

[tool.poetry.dependencies]
python = "3.11.8"
torch = "^2.2.0"
lightning = "^2.1.3"
tensordict = "^0.3.0"
jaxtyping = "^0.2.25"
beartype = "^0.17.0"
polars = "^0.20.6"
jaxlib = "^0.4.23"
flytekit = "^1.10.3"
rich = "^13.7.0"
faker = "^23.1.0"
tomli = "^2.0.1"
hydra-core = "^1.3.2"
humanize = "^4.9.0"
torchdata = "0.7.1"
avro = "^1.11.3"
fastavro = "^1.9.4"
msgspec = "^0.18.6"
fastparquet = "^2024.2.0"
funcy = "^2.0"
torchmetrics = "^1.3.1"
tensorboard = "^2.16.2"
onnx = "^1.15.0"
torch-tb-profiler = "^0.4.3"
metaflow = "^2.11.4"
param = "^2.0.2"
pdoc = "^14.4.0"
pytdigest = "^0.1.4"

[tool.poetry.group.dev.dependencies]
semver = "^3.0.2"
pre-commit = "^3.6.1"
ipykernel = "^6.29.3"
ruff = "^0.1.15"
pysort = "^1.0.0"
pytest = "^8.0.0"
pytest-cov = "^4.1.0"

[tool.ruff]
extend-ignore = ["F722"]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
